name: rooted_web
description: "Rooted Web Project"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  meta: ^1.10.0

  # UI
  cupertino_icons: ^1.0.2

  # IO
  email_validator: ^2.1.17

  # Network
  dio: ^5.4.0
  http_parser: ^4.0.2
  universal_html: ^2.2.4

  # Other
  cached_network_image: ^3.3.0
  maps_launcher: ^2.2.0
  url_launcher: ^6.2.1
  gap: ^3.0.1
  flutter_secure_storage: ^9.0.0
  syncfusion_flutter_sliders: ^24.1.41
  js: ^0.6.7
  fl_chart: ^0.66.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.0 # Code Generator
  flutter_launcher_icons: ^0.13.1 # Change App Icons
  flutter_lints: ^3.0.1 # Error Catching
  retrofit_generator: ^8.0.0 # Generating API Calls

flutter_launcher_icons:
  image_path: "assets/images/main_logo.png"
  web:
    generate: true
    image_path: "assets/images/main_logo.png"
    background_color: "#EFEFEA"
    theme_color: "#475E5E"

flutter:
  uses-material-design: true

  assets:
    - assets/images/main_logo.png
    - assets/images/socials/instagram.png
    - assets/images/socials/facebook.png
    - assets/images/socials/x.png
    - assets/images/socials/tiktok.png
    - assets/images/primary_gold_logo.png
    - assets/images/primary_white_logo.png
    - assets/images/logo_ivory.png
    - assets/images/icon_ivory.svg

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: LibreBaskerville
      fonts:
        - asset: assets/fonts/LibreBaskerville-Regular.ttf
