name: rooted_web
description: "Rooted Web Project"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  meta: ^1.10.0
  universal_html: ^2.2.4
  flutter_stripe: ^9.6.0
  flutter_stripe_web: ^4.6.0
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  email_validator: ^2.1.17
  http_parser: ^4.0.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/main_logo.png
    - assets/images/socials/instagram.png
    - assets/images/socials/facebook.png
    - assets/images/socials/x.png
    - assets/images/socials/tiktok.png

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: LibreBaskerville
      fonts:
        - asset: assets/fonts/LibreBaskerville-Regular.ttf

