name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.4' # Specify your Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          destination_dir: '.'  # Add this line if needed for your version of the action
          publish_branch: gh-pages  # Specify the branch to push to
